/* ===== Village Data Model ===== */

const MOOD_COLORS = {
  peaceful:  '#2ecc71',
  energized: '#f1c40f',
  stressed:  '#e74c3c',
  excited:   '#e67e22',
  lonely:    '#3498db',
  creative:  '#9b59b6',
};

const PULSE_COLORS = {
  active:   '#2ecc71',
  away:     '#f39c12',
  dnd:      '#e74c3c',
  sleeping: '#636e72',
};

const ACTIVITY_ICONS = {
  idle:       '💭',
  working:    '💻',
  commuting:  '🚶',
  gaming:     '🎮',
  cooking:    '🍳',
  sleeping:   '💤',
  exercising: '🏃',
  reading:    '📖',
  meditating: '🧘',
  traveling:  '✈️',
  studying:   '📚',
  music:      '🎵',
};

const FRIENDS = [
  {
    id: 'monk',
    name: 'Marcus',
    sprite: 'monk',
    mood: 'peaceful',
    status: '"Finding stillness in the chaos."',
    activity: 'meditating',
    location: 'Kyoto, Japan',
    timezone: 'JST (UTC+9)',
    pulse: 'active',
    bio: 'Tea ceremony enthusiast. Finds peace in the mountains. Has been practicing mindfulness for 8 years.',
    lastSeen: '2 min ago',
    friendSince: 'March 2022',
  },
  {
    id: 'elder',
    name: 'Nana Mae',
    sprite: 'elder',
    mood: 'peaceful',
    status: '"The garden is blooming nicely."',
    activity: 'cooking',
    location: 'Savannah, GA',
    timezone: 'EST (UTC-5)',
    pulse: 'active',
    bio: 'The Village Elder. Keeper of traditions and wisdom. Makes the best peach cobbler in three counties.',
    lastSeen: 'Just now',
    friendSince: 'January 2021',
    isElder: true,
  },
  {
    id: 'girl',
    name: 'Lily',
    sprite: 'girl',
    mood: 'excited',
    status: '"Just found the cutest café!"',
    activity: 'commuting',
    location: 'Seoul, South Korea',
    timezone: 'KST (UTC+9)',
    pulse: 'active',
    bio: 'Photographer & café hopper. Documenting every sunset she can find. Currently on a mission to visit 100 cafés.',
    lastSeen: '5 min ago',
    friendSince: 'June 2022',
  },
  {
    id: 'nerd',
    name: 'Oliver',
    sprite: 'nerd',
    mood: 'creative',
    status: '"Debugging the universe, one line at a time."',
    activity: 'working',
    location: 'Berlin, Germany',
    timezone: 'CET (UTC+1)',
    pulse: 'active',
    bio: 'Full-stack developer by day, indie game dev by night. Has 47 unfinished side projects.',
    lastSeen: '12 min ago',
    friendSince: 'September 2021',
  },
  {
    id: 'lumberjack',
    name: 'Erik',
    sprite: 'lumberjack',
    mood: 'energized',
    status: '"Morning run done. 10K in the bag!"',
    activity: 'exercising',
    location: 'Oslo, Norway',
    timezone: 'CET (UTC+1)',
    pulse: 'active',
    bio: 'Outdoor enthusiast and amateur woodworker. Believes every problem can be solved with a long hike.',
    lastSeen: '8 min ago',
    friendSince: 'April 2023',
  },
  {
    id: 'builder',
    name: 'James',
    sprite: 'builder',
    mood: 'energized',
    status: '"New project, new blueprint."',
    activity: 'working',
    location: 'Austin, TX',
    timezone: 'CST (UTC-6)',
    pulse: 'away',
    bio: 'Architect and maker. Currently restoring a 1920s bungalow. Coffee snob. Dog dad.',
    lastSeen: '45 min ago',
    friendSince: 'February 2022',
  },
  {
    id: 'ranger',
    name: 'Willow',
    sprite: 'ranger',
    mood: 'peaceful',
    status: '"Trail mix and trail maps."',
    activity: 'traveling',
    location: 'Patagonia, Chile',
    timezone: 'CLT (UTC-3)',
    pulse: 'away',
    bio: 'Wildlife biologist and park ranger. Currently on a research expedition. Loves stargazing and field journals.',
    lastSeen: '2 hours ago',
    friendSince: 'August 2021',
  },
  {
    id: 'bear',
    name: 'Kuma',
    sprite: 'bear',
    mood: 'peaceful',
    status: '"Zzz... five more minutes..."',
    activity: 'sleeping',
    location: 'Sapporo, Japan',
    timezone: 'JST (UTC+9)',
    pulse: 'sleeping',
    bio: 'Illustrator and plushie collector. Naps are sacred. Dreams in watercolor.',
    lastSeen: '3 hours ago',
    friendSince: 'November 2022',
  },
  {
    id: 'warrior',
    name: 'Aria',
    sprite: 'warrior',
    mood: 'energized',
    status: '"Kendo practice was intense today."',
    activity: 'exercising',
    location: 'Melbourne, Australia',
    timezone: 'AEST (UTC+10)',
    pulse: 'active',
    bio: 'Martial arts instructor and history buff. Collects antique swords. Fierce but kind.',
    lastSeen: '1 min ago',
    friendSince: 'May 2023',
  },
  {
    id: 'blonde',
    name: 'Sam',
    sprite: 'blonde',
    mood: 'creative',
    status: '"Writing chapter 12... almost there."',
    activity: 'working',
    location: 'Portland, OR',
    timezone: 'PST (UTC-8)',
    pulse: 'dnd',
    bio: 'Aspiring novelist and barista. Currently writing a fantasy trilogy. Please do not disturb during writing hours.',
    lastSeen: '30 min ago',
    friendSince: 'July 2022',
  },
  {
    id: 'kid',
    name: 'Milo',
    sprite: 'kid',
    mood: 'excited',
    status: '"NEW HIGH SCORE!!!"',
    activity: 'gaming',
    location: 'Toronto, Canada',
    timezone: 'EST (UTC-5)',
    pulse: 'active',
    bio: 'College student and competitive gamer. Streams on weekends. Always up for a co-op session.',
    lastSeen: 'Just now',
    friendSince: 'October 2023',
  },
  {
    id: 'guard',
    name: 'Dante',
    sprite: 'guard',
    mood: 'stressed',
    status: '"Deadline Friday. Send coffee."',
    activity: 'working',
    location: 'Lagos, Nigeria',
    timezone: 'WAT (UTC+1)',
    pulse: 'active',
    bio: 'UX designer at a fintech startup. Night owl. Makes incredible jollof rice.',
    lastSeen: '7 min ago',
    friendSince: 'December 2021',
  },
];

const QUESTS = {
  weeklyTraditions: [
    {
      id: 'morning-brew',
      title: 'The Morning Brew',
      description: 'Share a photo of your morning drink every day this week. Unlock the "Caffeinated" status!',
      icon: '☕',
      participants: ['monk', 'girl', 'nerd', 'blonde'],
      progress: 5,
      total: 7,
      deadline: 'Sun, Apr 12',
      status: 'active',
    },
    {
      id: 'sunset-snap',
      title: 'Sunset Snap',
      description: 'Capture the sunset from your location and share it with the village.',
      icon: '🌅',
      participants: ['ranger', 'lumberjack', 'warrior', 'girl', 'guard'],
      progress: 3,
      total: 5,
      deadline: 'Fri, Apr 10',
      status: 'active',
    },
    {
      id: 'recipe-swap',
      title: 'Recipe Swap',
      description: 'Everyone cooks the same recipe this week and shares the results. This week: homemade pasta!',
      icon: '🍝',
      participants: ['elder', 'builder', 'kid', 'guard', 'monk'],
      progress: 4,
      total: 5,
      deadline: 'Sat, Apr 11',
      status: 'active',
    },
  ],
  monthlyExpeditions: [
    {
      id: 'horizon-line',
      title: 'The Horizon Line',
      description: 'Each friend photographs their horizon at sunset. When all are collected, a shared panorama is created.',
      icon: '🌄',
      participants: ['ranger', 'warrior', 'lumberjack', 'builder', 'girl'],
      progress: 3,
      total: 5,
      deadline: 'Apr 30',
      status: 'active',
    },
    {
      id: 'bookworms',
      title: 'Bookworms Unite',
      description: 'Read the same book and share weekly reactions. This month: "The Midnight Library" by Matt Haig.',
      icon: '📚',
      participants: ['blonde', 'nerd', 'monk', 'elder', 'guard', 'bear'],
      progress: 2,
      total: 4,
      deadline: 'Apr 30',
      status: 'active',
    },
  ],
  elderSuggestion: {
    id: 'voice-garden',
    title: 'The Voice Garden',
    description: 'Leave a 30-second voice note for each friend in your village. Watch the flowers bloom as notes are exchanged!',
    icon: '🌸',
    participants: [],
    progress: 0,
    total: 12,
    deadline: 'Apr 20',
    status: 'suggested',
  },
};

const MEMORIES = [
  {
    id: 'm1',
    type: 'quest-complete',
    questTitle: 'Recipe Swap Vol. 3',
    date: 'March 2026',
    participants: ['girl', 'elder', 'blonde', 'monk'],
    thumbnail: 'sprites/elder.png',
    description: 'We all made Nana Mae\'s famous peach cobbler. Marcus burned his twice but the third attempt was perfection. Lily added a Korean twist with yuzu zest.',
    hasVoiceNote: true,
  },
  {
    id: 'm2',
    type: 'quest-complete',
    questTitle: 'The Horizon Line — February',
    date: 'February 2026',
    participants: ['ranger', 'warrior', 'lumberjack', 'girl', 'guard'],
    thumbnail: 'sprites/ranger.png',
    description: 'Five horizons from five continents stitched into one panorama. Willow\'s Patagonian sky stole the show.',
    hasVoiceNote: false,
  },
  {
    id: 'm3',
    type: 'quest-complete',
    questTitle: 'The Morning Brew — Week 8',
    date: 'February 2026',
    participants: ['monk', 'nerd', 'blonde', 'kid'],
    thumbnail: 'sprites/monk.png',
    description: 'Oliver tried Marcus\'s matcha recipe and actually loved it. Sam\'s latte art is getting impressive.',
    hasVoiceNote: true,
  },
  {
    id: 'm4',
    type: 'milestone',
    questTitle: 'Village Anniversary',
    date: 'January 2026',
    participants: ['monk', 'elder', 'girl', 'nerd', 'lumberjack', 'builder', 'ranger', 'bear', 'warrior', 'blonde', 'kid', 'guard'],
    thumbnail: 'sprites/girl.png',
    description: 'One year since the full village assembled. We did a synchronized video call across 8 time zones. Kuma fell asleep halfway through (on brand).',
    hasVoiceNote: true,
  },
  {
    id: 'm5',
    type: 'quest-complete',
    questTitle: 'Sunset Snap — December',
    date: 'December 2025',
    participants: ['girl', 'lumberjack', 'guard', 'warrior'],
    thumbnail: 'sprites/warrior.png',
    description: 'Winter sunsets hit different. Aria caught the Melbourne summer glow while Erik had northern twilight. Beautiful contrast.',
    hasVoiceNote: false,
  },
  {
    id: 'm6',
    type: 'quest-complete',
    questTitle: 'Bookworms Unite — Vol. 1',
    date: 'November 2025',
    participants: ['blonde', 'nerd', 'monk', 'elder'],
    thumbnail: 'sprites/blonde.png',
    description: 'Our first book club pick: "Klara and the Sun." Sam wrote a 3-page reaction essay. Nana Mae said it reminded her of her grandmother\'s stories.',
    hasVoiceNote: true,
  },
  {
    id: 'm7',
    type: 'quest-complete',
    questTitle: 'Fitness Frenzy',
    date: 'October 2025',
    participants: ['lumberjack', 'warrior', 'kid', 'guard'],
    thumbnail: 'sprites/lumberjack.png',
    description: 'Combined step count: 847,000 steps in one month. Erik basically carried the team with his hiking obsession.',
    hasVoiceNote: false,
  },
  {
    id: 'm8',
    type: 'milestone',
    questTitle: 'First Village Quest',
    date: 'August 2025',
    participants: ['monk', 'elder', 'girl', 'nerd'],
    thumbnail: 'sprites/nerd.png',
    description: 'The OG four completed the very first Morning Brew challenge. The tradition that started it all.',
    hasVoiceNote: true,
  },
];

const NOTIFICATIONS = [
  { id: 'n1', sprite: 'warrior', text: 'Aria changed mood to Energized', time: '5 min ago', unread: true },
  { id: 'n2', sprite: 'girl', text: 'Lily completed Sunset Snap Day 3', time: '12 min ago', unread: true },
  { id: 'n3', sprite: 'elder', text: 'The Elder has a new quest suggestion!', time: '30 min ago', unread: true },
  { id: 'n4', sprite: 'monk', text: 'Marcus shared a Morning Brew photo', time: '1 hour ago', unread: false },
  { id: 'n5', sprite: 'nerd', text: 'Oliver finished Chapter 3 of Bookworms', time: '2 hours ago', unread: false },
  { id: 'n6', sprite: 'kid', text: 'Milo beat his high score!', time: '3 hours ago', unread: false },
  { id: 'n7', sprite: 'blonde', text: 'New memory added to Town Square', time: '5 hours ago', unread: false },
  { id: 'n8', sprite: 'lumberjack', text: 'Erik completed a 15K trail run', time: '8 hours ago', unread: false },
];

// Helper to get friend data by sprite ID
function getFriend(id) {
  return FRIENDS.find(f => f.id === id);
}

// Helper to get mood color
function getMoodColor(mood) {
  return MOOD_COLORS[mood] || '#888';
}

// Helper to get activity icon
function getActivityIcon(activity) {
  return ACTIVITY_ICONS[activity] || '💭';
}
